#!/bin/bash

# TODO: Check installed command
#       1. curl or wget
#       2. jq or sed, awk

# 引数チェック
if [ $# -ne 1 ]; then
cat << HELP
    docker-search  --  list all tags for a Docker image on a remote registry.

    EXAMPLE: 
        - list all tags for ubuntu:
        docker-search ubuntu
HELP
else
    image="$1"
    tags=`curl -s https://registry.hub.docker.com/v1/repositories/${image}/tags | jq '.[].name'`
    # tags=`wget -q https://registry.hub.docker.com/v1/repositories/${image}/tags -O - | sed -e 's/[][]//g' -e 's/"//g' -e 's/ //g' | tr '}' '\n' | awk -F: '{print $3}'`

    echo "${tags}"
fi
